version: 2
updates:
  # Maintain dependencies for Docker images

  - package-ecosystem: "docker"
    directory: "/images/haproxy"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/images/traefik"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/images/vaultwarden"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
