Port: 8080
ExternalPort: 443
ExternalSecure: true
# TLS is handled by Traefik
TLS:
  Enabled: false

Database:
  postgres:
    Host: postgres-ha
    Port: 5432
    Database: zitadel
    User:
      Username: zitadel
      Password: "env:ZITADEL_DATABASE_POSTGRES_USER_PASSWORD"
      SSL:
        Mode: disable
    Admin:
      Username: postgres
      Password: "env:ZITADEL_ADMIN_PASSWORD"
      SSL:
        Mode: disable
      SSL:
        Mode: disable

Log:
  Level: info

# Telemetry and Metrics
Telemetry:
  Metrics:
    Enabled: true
